A: CONST 5

LLLLLLLLLLLLLLlllllLLasafLLLLLfasLLLLLLLvzxvLLLLxLLLLLLLLsdafLLLLLLLLLLLfasFASFAaLvxLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL: 
        
        
        LOAD A
ADD A
STORE B
STOP
B: SPACE
