; test_norm_macro_with_plus.asm
; test macro that contains plus expressions
ADDMACRO: MACRO BASE, OFFSET
LOAD BASE+OFFSET
STORE RESULT
ENDMACRO

ADDMACRO VAL  ,  1
ADDMACRO VAL2+1,2
VAL: CONST 100
VAL2: CONST 200
RESULT: SPACE 1