LLLLLLLLLLLLLLlllllLLasafLLLLLfasLLLLLLLvzxvLLLLxLLLLLLLLsdafLLLLLLLLLLLfasFASFAaLvxLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL: 
        LOAD A
ADD A
STORE B
STOP
A: CONST 10
B: SPACE
