; Teste de caso extremo - macro que usa várias outras macros
; Macro básica 1
LOAD_AND_ADD: MACRO VAR NUM
    LOAD VAR
    ADD NUM
ENDMACRO

; Macro básica 2  
STORE_RESULT: MACRO DEST
    STORE DEST
ENDMACRO

; Macro que combina as duas anteriores
CALC_AND_STORE: MACRO SRC NUM DEST
    LOAD_AND_ADD SRC NUM
    STORE_RESULT DEST
ENDMACRO

; Macro que usa CALC_AND_STORE múltiplas vezes
BATCH_CALC: MACRO A B C
    CALC_AND_STORE A NUM1 RESULT1
    CALC_AND_STORE B NUM2 RESULT2  
    CALC_AND_STORE C NUM3 RESULT3
ENDMACRO

; Programa principal
BATCH_CALC INPUT1 INPUT2 INPUT3
OUTPUT RESULT1
OUTPUT RESULT2
OUTPUT RESULT3
STOP

INPUT1: CONST 10
INPUT2: CONST 20
INPUT3: CONST 30
NUM1: CONST 5
NUM2: CONST 15
NUM3: CONST 25
RESULT1: SPACE
RESULT2: SPACE
RESULT3: SPACE
